# -*- coding: utf-8 -*-
"""App

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1duAU8LaFrC5mUXdiZwtD8gdsGThULQdF
"""

# --- GRADIO INTERFACE SECTION ---
import gradio as gr
from PIL import Image
import numpy as np

# Ensure idx_to_class is available from your previous training steps
# If the previous cells ran correctly, 'idx_to_class' and 'model' are already in memory.

def classify_image(image):
    if image is None:
        return None

    # 1. Preprocess the image to match MobileNetV2 requirements
    # Resize to (224, 224) as defined in your IMG_SIZE
    img = image.resize((224, 224))

    # Convert to numpy array
    x = np.array(img).astype(np.float32)

    # Apply the same preprocessing used during training
    x = preprocess_input(x)

    # Expand dimensions to fit model input (1, 224, 224, 3)
    x = np.expand_dims(x, axis=0)

    # 2. Make Prediction
    probs = model.predict(x, verbose=0)[0]

    # 3. Return dictionary for Gradio Label
    # Format: { "Class Name": Probability, ... }
    results = {idx_to_class[i]: float(probs[i]) for i in range(len(probs))}

    return results

# Create the Gradio Interface
interface = gr.Interface(
    fn=classify_image,
    inputs=gr.Image(type="pil", label="Upload Product Image"),
    outputs=gr.Label(num_top_classes=5, label="Predictions"),
    title="Pharmaceutical Product Classifier",
    description="Upload an image of a pharmaceutical product package to classify it. The model will show the top 5 probable classes.",
    theme="default",
    examples=None # You can add file paths here like ['example1.jpg'] if you have them
)

# Launch the app
# share=True creates a public link (useful for Colab)
interface.launch(share=True, debug=True)